---
- name: Update Packages and Send Report
  hosts: server
  gather_facts: yes  # Gather facts about target hosts

  tasks:
    - name: Get current package list
      shell: rpm -qa --qf "%{NAME},%{VERSION}\n"
      register: current_packages

    - name: Upgrade all packages excluding MONGO, HTTPD, DOCKER
      yum:
        name: '*'
        exclude: mongo*,httpd*,docker*
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_updates

    - name: Get updated package list
      shell: rpm -qa --qf "%{NAME},%{VERSION}\n"
      register: updated_packages

    - name: Generate CSV file of package report
      set_fact:
        package_report: |
          VM IP Address,Package Name,Before Update,After Update,Updated_Version
          {% for current, updated in current_packages.stdout_lines | zip(updated_packages.stdout_lines) %}
          {{ ansible_host }},{{ current }},{{ updated }}
          {% endfor %}
      delegate_to: localhost

    - name: Create CSV file
      delegate_to: localhost
      #run_once: true
      copy:
        content: "{{ package_report }}"
        dest: "/tmp/package_report_{{ ansible_host }}.csv"

    - name: Send Email
      delegate_to: localhost
      mail:
        host: smtp.gmail.com # Update with your SMTP server details
        port: 587
        username: no-reply@it22.nl 
        password: 
        to: h.tahir@it22.nl
        subject: Package Update Report
        body: Attached is the CSV file containing package update report.
        attach:
          - /tmp/package_report_{{ ansible_host }}.csv
      when: package_report | length > 0
